import 'package:awesome_bottom_bar/awesome_bottom_bar.dart';
import 'package:flutter/material.dart';
import 'package:lazy_read_app/core/constants/app_colors.dart';
import 'package:lazy_read_app/presentation/srceens/general/Categories/categories.dart';
import 'package:lazy_read_app/presentation/srceens/general/add_post/add_post.dart';
import 'package:lazy_read_app/presentation/srceens/general/home/home.dart';
import 'package:lazy_read_app/presentation/srceens/general/profile/profile.dart';
import 'package:lazy_read_app/presentation/srceens/general/tags/tags.dart';
part 'general.dart';
